package br.com.fiap.petbuddies.domain.enums;

public enum AcaoPendente {
    AGENDAMENTO_AGUARDANDO_ESCOLHA_ANIMAL,
    AGENDAMENTO_AGUARDANDO_TURNO,
    AGENDAMENTO_AGUARDANDO_ESCOLHA_JANELA,
    AGENDAMENTO_AGUARDANDO_CONFIRMACAO
}
