package br.com.fiap.petbuddies.domain.enums;

public enum TriagemStage {
    TRIAGEM_IDENTIFICANDO_ANIMAL,
    TRIAGEM_AGUARDANDO_P1,
    TRIAGEM_AGUARDANDO_P2,
    TRIAGEM_AGUARDANDO_P3,
    TRIAGEM_AGUARDANDO_P4,
    TRIAGEM_FINALIZADA,
    TRIAGEM_OFERECEU_AGENDAMENTO
}
