// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetBuddies_API.Data;

#nullable disable

namespace PetBuddies_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260520010144_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetBuddies_API.Models.AnimalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CT_CASTRADO");

                    b.Property<bool>("CondicaoCronica")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CN_CONDICAO_CRONICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_DATA_NASCIMENTO");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("FT_FOTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_ANIMAL");

                    b.Property<decimal>("Peso")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("NR_PESO");

                    b.Property<bool>("PreCadastro")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PC_PRE_CADASTRO");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SX_SEXO");

                    b.Property<int>("TipoAnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_ANIMAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("TipoAnimalId");

                    b.ToTable("T_PB_ANIMAL");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ClinicaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("NVARCHAR2(254)")
                        .HasColumnName("EM_EMAIL");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_CLINICA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TL_TELEFONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("T_PB_CLINICA");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ConsultaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DH_DATA_HORA");

                    b.Property<bool>("Emergencia")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EM_EMERGENCIA");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MT_MOTIVO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACAO");

                    b.Property<bool>("Prioridade")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PR_PRIORIDADE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ST_STATUS_CONSULTA");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_TIPO_CONSULTA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_PB_CONSULTA");
                });

            modelBuilder.Entity("PetBuddies_API.Models.EnderecoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENDERECO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("BR_BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("NR_CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CD_CIDADE");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CM_COMPLEMENTO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("ES_ESTADO");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("LG_LOGRADOURO");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_NUMERO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("T_PB_ENDERECO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.JanelaAtendimentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_JANELA_ATENDIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DH_DATA_HORA_FIM");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DH_DATA_HORA_INICIO");

                    b.Property<int>("DuracaoSlot")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DR_DURACAO_SLOT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_PB_JANELA_ATENDIMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ProcedimentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROCEDIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnexosUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("AN_ANEXOS_URL");

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataPrevistaFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DATA_PREVISTA_FIM");

                    b.Property<DateTime>("DataPrevistaInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DATA_PREVISTA_INICIO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACAO");

                    b.Property<int>("RegistroAtendimentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO_ATENDIMENTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ST_STATUS_PROCEDIMENTO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_TIPO_PROCEDIMENTO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("RegistroAtendimentoId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_PB_PROCEDIMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ProntuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRONTUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_ALERGIA");

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACOES");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.ToTable("T_PB_PRONTUARIO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegistroAtendimentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO_ATENDIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anamnese")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AN_ANAMNESE");

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DATA_ATENDIMENTO");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DG_DIAGNOSTICO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACAO");

                    b.Property<int>("ProntuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRONTUARIO");

                    b.Property<string>("ProximaVacina")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PR_PROXIMA_VACINA");

                    b.Property<string>("ProximoRetorno")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PR_PROXIMO_RETORNO");

                    b.Property<string>("Tratamento")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TR_TRATAMENTO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.HasIndex("ProntuarioId");

                    b.ToTable("T_PB_REGISTRO_ATENDIMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ResponsavelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("NVARCHAR2(254)")
                        .HasColumnName("EM_EMAIL");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_RESPONSAVEL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ST_STATUS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TL_TELEFONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("T_PB_RESPONSAVEL");
                });

            modelBuilder.Entity("PetBuddies_API.Models.TipoAnimalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_ANIMAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ES_ESPECIE");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PT_PORTE");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RC_RACA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("T_PB_TIPO_ANIMAL");
                });

            modelBuilder.Entity("PetBuddies_API.Models.VeterinarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AtendeEmergencia")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("AE_ATENDE_EMERGENCIA");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("AT_ATIVO");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NR_CRMV");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("NVARCHAR2(254)")
                        .HasColumnName("EM_EMAIL");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ES_ESPECIALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_VETERINARIO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TL_TELEFONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("T_PB_VETERINARIO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.AnimalEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ResponsavelEntity", "Responsavel")
                        .WithMany("Animais")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.TipoAnimalEntity", "TipoAnimal")
                        .WithMany("Animais")
                        .HasForeignKey("TipoAnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ClinicaEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.EnderecoEntity", "Endereco")
                        .WithOne("Clinica")
                        .HasForeignKey("PetBuddies_API.Models.ClinicaEntity", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ConsultaEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("Consultas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.ClinicaEntity", "Clinica")
                        .WithMany("Consultas")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Clinica");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.JanelaAtendimentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany("JanelasAtendimento")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ProcedimentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("Procedimentos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.RegistroAtendimentoEntity", "RegistroAtendimento")
                        .WithMany("Procedimentos")
                        .HasForeignKey("RegistroAtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany("Procedimentos")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("RegistroAtendimento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ProntuarioEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithOne("Prontuario")
                        .HasForeignKey("PetBuddies_API.Models.ProntuarioEntity", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegistroAtendimentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("RegistroAtendimentos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.ConsultaEntity", "Consulta")
                        .WithOne("RegistroAtendimento")
                        .HasForeignKey("PetBuddies_API.Models.RegistroAtendimentoEntity", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.ProntuarioEntity", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Consulta");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ResponsavelEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ClinicaEntity", "Clinica")
                        .WithMany("Responsaveis")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.EnderecoEntity", "Endereco")
                        .WithMany("Responsaveis")
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Clinica");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetBuddies_API.Models.VeterinarioEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ClinicaEntity", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetBuddies_API.Models.AnimalEntity", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Procedimentos");

                    b.Navigation("Prontuario");

                    b.Navigation("RegistroAtendimentos");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ClinicaEntity", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Responsaveis");

                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ConsultaEntity", b =>
                {
                    b.Navigation("RegistroAtendimento");
                });

            modelBuilder.Entity("PetBuddies_API.Models.EnderecoEntity", b =>
                {
                    b.Navigation("Clinica");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegistroAtendimentoEntity", b =>
                {
                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ResponsavelEntity", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("PetBuddies_API.Models.TipoAnimalEntity", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("PetBuddies_API.Models.VeterinarioEntity", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("JanelasAtendimento");

                    b.Navigation("Procedimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
